---
title: "trial_app"
output: html_document
date: "2024-07-30"
---

```{r }
library(tidyverse)
library(metafor)

library(sjPlot)
library(sjmisc)
library(sjlabelled)
```



```{r}
study_data <- data.frame(
  StudyID = c("Carter2005", "Trujillo1984", "Kemp2015", "Brotsker1995"),
  MeanControl = c(26.1, 38, 58, 69.5),
  SampleSizeControl = c(18, 24, 15, 18),
  SDControl = c(29.7, 15.19, 8.52, 15.7),
  MeanTreatment = c(84.8, 112.1, 118.4, 117.4),
  SampleSizeTreatment = c(12, 14, 12, 9),
  SDTreatment = c(28.06, 35.17, 27.71, 18.6)
)

escalc_results<-escalc(
      measure = "SMD", 
      m1i = study_data$MeanTreatment, 
      sd1i = study_data$SDTreatment, 
      n1i = study_data$SampleSizeTreatment, 
      m2i = study_data$MeanControl, 
      sd2i = study_data$SDControl, 
      n2i = study_data$SampleSizeControl,
      slab = study_data$StudyID,
      data = study_data
    )

data.frame(escalc_results)

data.frame(summary(escalc_results))

res<-rma(yi, vi, data = escalc_results)

summary(res)

print(summary(res))


res$fit.stats
```
```{r}

  logLik <- res$fit.stats$REML[1]
  deviance <- res$fit.stats$REML[2]
  aic <- res$fit.stats$REML[3]
  bic <- res$fit.stats$REML[4]
  aicc <- res$fit.stats$REML[5]
  tau2 <- res$tau2
  tau <- sqrt(tau2)
  i2 <- res$I2
  h2 <- 1 / (1 - res$I2 / 100)
  qtest <- res$QE
  qdf <- res$k - 1
  q_pval <- res$QEp
  coef <- res$b
  se <- res$se
  zval <- coef / se
  pval <- 2 * pnorm(-abs(zval))
  if(pval<.0001){
    pval<-"<.0001"
    } else {pval<-round(pval,4)}
  ci.ub <- res$ci.ub
  ci.lb <- res$ci.lb
  
  # Format output
  cat("Random-Effects Model (k =", res$k, "; tau^2 estimator: REML)\n\n")
  
  cat("Model Fit Statistics:\n\n")
cat(paste0("logLik: ",round(logLik,4),"\n"))
cat(paste0("Deviance: ",round(deviance,4),"\n"))
cat(paste0("AIC: ",round(aic,4),"\n"))
cat(paste0("BIC: ",round(bic,4),"\n"))
cat(paste0("AICC: ",round(aicc,4),"\n\n"))

  
  cat(sprintf("tau^2 (estimated amount of total heterogeneity): %6.4f (SE = %6.4f)\n", tau2, res$se.tau))
  cat(sprintf("tau (square root of estimated tau^2 value):      %6.4f\n", tau))
  cat(sprintf("I^2 (total heterogeneity / total variability):   %5.2f%%\n", i2))
  cat(sprintf("H^2 (total variability / sampling variability):  %5.2f\n\n", h2))
  
  cat("Test for Heterogeneity:\n\n")
  cat(sprintf("Q(df = %d) = %6.4f, p-val = %6.4f\n\n", qdf, qtest, q_pval))
  
  cat("Model Results:\n\n")
  
cat(paste0("estimate: ",round(coef,4),"\n"))
cat(paste0("se: ",round(se,4),"\n"))
cat(paste0("zval: ",round(zval,4),"\n"))
cat(paste0("pval: ",pval,"\n"))
cat(paste0("ci.lb: ",round(ci.lb,4),"\n"))
cat(paste0("ci.ub: ",round(ci.ub,4),"\n\n"))

```


```{r message=FALSE, warning=FALSE}
data<-bind_rows(coef(summary(res))%>% rownames_to_column(var = "StudyID") %>% select(StudyID,estimate,ci.lb,ci.ub) %>% rename(yi=estimate) %>% mutate(y_order=1),
      data.frame(summary(escalc_results)) %>% mutate(y_order=(1:n())+2)) %>% 
  merge(.,data.frame(weights(res)) %>% rownames_to_column(var = "StudyID"),by="StudyID",all.x=T) %>% 
  mutate(StudyID=ifelse(StudyID=="intrcpt","Total (95% CI)",StudyID)) %>% 
    mutate(total_n=SampleSizeTreatment+SampleSizeControl)

#x scale
if(ceiling(max(data$ci.ub)-min(data$ci.lb))<=7){
  seq<-1
} else {
  seq<-2
}

#minimum x scale
  if(min(data$ci.lb)<0 & seq==2){
    min_x<-floor(min(data$ci.lb)/ 2) * 2    
  } else if (min(data$ci.lb)<0) {
    min_x<-0
  }

#maximum

#breaks interval

data %>% 
  ggplot(aes(x=yi,y=(y_order)))+
  geom_vline(xintercept=0,linetype="dashed")+
  geom_point(aes(size=total_n),shape=15)+
  geom_errorbar(aes(xmin=ci.lb,xmax=ci.ub),width=0.1)+
  geom_text(aes(label=paste0(round(yi,2)," [",round(ci.lb,2)," - ",round(ci.ub,2),"]"),x=max(ci.ub)+1.5),hjust=0)+
  geom_text(aes(label=StudyID,x=min(ci.lb)-3),hjust=0)+
  theme_minimal()+
  theme(
    legend.position = "none",
    axis.text.y = element_blank(),
    axis.title.y = element_blank(),
    panel.grid = element_blank()
  )+
  coord_cartesian(xlim=c(0-2,max(data$ci.ub+3)))




```
Heterogeneity Q, df, I2, pvalue

```{r}
print(max(data$ci.ub))
print(min(data$ci.lb))
print(max(data$ci.ub) - min(data$ci.lb))
print(ceiling(max(data$ci.ub) - min(data$ci.lb)))

if (ceiling(max(data$ci.ub) - min(data$ci.lb)) <= 7) {
  seq <- 1
} else {
  seq <- 2
}

print(seq)
```



```{r}
dat <- data.frame(author = c("Dyson", "Jönsson", "Morris", "Saslow", "Saslow", "Sato", "Tay", "Yamada"),
                  year   = c(2010, 2009, 2019, 2014, 2017, 2017, 2014, 2014),
                  ai     = c(3, 6, 11, 8, 6, 4, 36, 2),
                  n1i    = c(6, 6, 21, 9, 11, 22, 46, 12),
                  ci     = c(1, 3, 0, 5, 0, 0, 30, 2),
                  n2i    = c(6, 6, 12, 13, 8, 27, 47, 12))
 
### calculate risk differences and corresponding sampling variances (and use
### the 'slab' argument to store study labels as part of the data frame)
dat <- escalc(measure="RD", ai=ai, n1i=n1i, ci=ci, n2i=n2i, data=dat,
              slab=paste(" ", author, year), addyi=FALSE)
dat
 
### fit random-effects model (using the DL estimator)
res <- rma(yi, vi, data=dat, method="DL")
res
 
############################################################################
 
### colors to be used in the plot
colp <- "#6b58a6"
coll <- "#a7a9ac"
 
### total number of studies
k <- nrow(dat)
 
### generate point sizes
psize <- weights(res)
psize <- 1.2 + (psize - min(psize)) / (max(psize) - min(psize))
 
### get the weights and format them as will be used in the forest plot
weights <- weights(res)
 
### adjust the margins
par(mar=c(2.7,3.2,2.3,1.3), mgp=c(3,0,0), tcl=0.15)
 
### forest plot with extra annotations
forest(dat$yi, dat$vi, xlim=c(-3.4,2.1), ylim=c(-0.5,k+3), alim=c(-1,1), cex=0.88,
              pch=18, psize=psize, efac=0, refline=NA, lty=c(1,0), xlab="",
              ilab=cbind(paste(dat$ai, "/", dat$n1i), paste(dat$ci, "/", dat$n2i),weights),
              ilab.xpos=c(-1.9,-1.3,1.2), annosym=c(" (", " to ", ")"),
              rowadj=-.07)
 
### add the vertical reference line at 0
segments(0, -1, 0, k+1.6, col=coll)
 
### add the vertical reference line at the pooled estimate
segments(coef(res), 0, coef(res), k, col=colp, lty="33", lwd=0.8)
 
### redraw the CI lines and points in the chosen color
segments(summary(dat)$ci.lb, k:1, summary(dat)$ci.ub, k:1, col=colp, lwd=1.5)
points(dat$yi, k:1, pch=18, cex=psize*1.15, col="white")
points(dat$yi, k:1, pch=18, cex=psize, col=colp)
 
### add the summary polygon
addpoly(res, row=0, mlab="Total (95% CI)", efac=2, col=colp, border=colp)
 
### add the horizontal line at the top
abline(h=k+1.6, col=coll)
 
### redraw the x-axis in the chosen color
axis(side=1, at=seq(-1,1,by=0.5), col=coll, labels=FALSE)
 
### now we add a bunch of text; since some of the text falls outside of the
### plot region, we set xpd=NA so nothing gets clipped
par(xpd=NA)
 
### adjust cex as used in the forest plot and use a bold font
par(cex=sav$cex, font=2)
 
### add headings
text(sav$xlim[1], k+2.5, pos=4, "Study or\nsubgroup")
text(sav$ilab.xpos[1:2], k+2.3, c("Experimental","Control"))
text(mean(sav$ilab.xpos[1:2]), k+3.4, "No of events / total")
text(0, k+2.7, "Risk difference, IV,\nrandom (95% CI)")
segments(sav$ilab.xpos[1]-0.22, k+2.8, sav$ilab.xpos[2]+0.13, k+2.8)
text(c(sav$ilab.xpos[3],sav$xlim[2]-0.35), k+2.7, c("Weight\n(%)","Risk difference, IV,\nrandom (95% CI)"))
 
### add 'Favours control'/'Favours experimental' text below the x-axis
text(c(-1,1), -2.5, c("Favors control","Favors experimental"), pos=c(4,2), offset=-0.3)
 
### use a non-bold font for the rest of the text
par(cex=sav$cex, font=1)
 
### add the 100.0 for the sum of the weights
text(sav$ilab.xpos[3], 0, "100.0")
 
### add the column totals for the counts and sample sizes
text(sav$ilab.xpos[1:2], 0, c(paste(sum(dat$ai), "/", sum(dat$n1i)), paste(sum(dat$ci), "/", sum(dat$n2i))))
 
### add text with heterogeneity statistics
text(sav$xlim[1], -1, pos=4, bquote(paste("Test for heterogeneity: ",
   tau^2, "=", .(fmtx(res$tau2, digits=2)), "; ",
   chi^2, "=", .(fmtx(res$QE, digits=2)),
   ", df=", .(res$k - res$p), ", ",
   .(fmtp(res$QEp, digits=2, pname="P", add0=TRUE, equal=TRUE)), "; ",
   I^2, "=", .(round(res$I2)), "%")))
 
### add text for test of overall effect
text(sav$xlim[1], -2, pos=4, bquote(paste("Test for overall effect: ",
   "Z=", .(fmtx(res$zval, digits=2)), ", ",
   .(fmtp(res$pval, digits=3, pname="P", add0=TRUE, equal=TRUE)))))
```




















